<?php
/**
 * Plugin Name: HYREME Core Features
 * Description: Custom platform logic, including Recruiter email validation and Dark Mode UI styling.
 * Version: 1.1
 * Author: Areeb
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/* ==========================================================================
   1. RECRUITER EMAIL RESTRICTION (Business Emails Only)
   ========================================================================== */
add_action('um_submit_form_errors_hook_', 'hyreme_restrict_recruiter_email', 10, 1);

function hyreme_restrict_recruiter_email( $args ) {
    // Check if the user is trying to register as a Recruiter (Role ID: recruiter)
    if ( isset( $args['role'] ) && $args['role'] === 'recruiter' ) {
        
        $banned_domains = array('gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'aol.com', 'icloud.com');
        
        if ( isset( $args['user_email'] ) ) {
            $email = $args['user_email'];
            $domain = substr(strrchr($email, "@"), 1);
            
            if ( in_array( strtolower( $domain ), $banned_domains ) ) {
                UM()->form()->add_error( 'user_email', 'Recruiters must use a professional/company email address to join HYREME.' );
            }
        }
    }
}

/* ==========================================================================
   2. PREMIUM DARK MODE UI FOR AUTHENTICATION PAGES
   ========================================================================== */
add_action('wp_head', 'hyreme_custom_dark_ui_css');

function hyreme_custom_dark_ui_css() {
    // We only want to inject this CSS on the Login (10) and Register (11) pages.
    // Make sure these IDs match the actual page IDs generated by Ultimate Member in your install.
    if ( is_page( array( 10, 11 ) ) ) {
        ?>
        <style>
            /* HYREME Dark Mode Global Override */
            body {
                background-color: #0c0c0e !important;
            }
            
            /* Ultimate Member Form Styling */
            .um {
                max-width: 400px !important;
                margin: 8vh auto !important;
                background: #16161a !important;
                padding: 40px !important;
                border-radius: 24px !important;
                border: 1px solid #2a2a32 !important;
                box-shadow: 0 20px 40px rgba(0,0,0,0.6) !important;
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif !important;
            }
            
            /* Input Fields */
            .um .um-form input[type=text], 
            .um .um-form input[type=password], 
            .um .um-form input[type=email] {
                background-color: #212127 !important;
                border: 1px solid #33333b !important;
                color: #ffffff !important;
                border-radius: 12px !important;
                padding: 16px !important;
                font-size: 15px !important;
            }
            
            /* Input Focus State */
            .um .um-form input:focus {
                border-color: #0056b3 !important;
                outline: none !important;
            }
            
            /* Labels */
            .um-field-label {
                color: #a0a0a8 !important;
                font-weight: 500 !important;
                font-size: 13px !important;
            }
            
            /* Submit Button */
            .um .um-button {
                background: #0056b3 !important;
                border-radius: 12px !important;
                padding: 16px !important;
                font-weight: 600 !important;
                text-transform: uppercase !important;
                letter-spacing: 1px !important;
                color: #fff !important;
                transition: all 0.3s ease !important;
                width: 100% !important;
            }
            
            /* Button Hover */
            .um .um-button:hover {
                background: #004494 !important;
                transform: translateY(-2px) !important;
            }
            
            /* Hide WordPress Header/Footer elements cleanly on Auth pages */
            .page-id-10 header, .page-id-11 header, .page-id-10 footer, .page-id-11 footer {
                display: none !important;
            }
        </style>
        <?php
    }
}
?>
